### ISSUE TITLE
Regarding the issue of playing large MP4 files

### ISSUE THREAD

**Issue by Nreko** [yabadabu/dx11_video_texture#3]
Thank you very much for your open source project. I noticed that when I tried to play a 2GB MP4 file, the system memory seemed to slowly increase until it was fully released after the file finished playing, effectively using up 2GB of memory which is the same size as the file. This doesn't seem optimal for larger MP4 files. I was wondering if this is caused by a memory leak?

**Comment by yabadabu** [comment]
Hi
OK, I found two leaks in the code!!
- In the destructor of the videoplayer object, on the video texture object, but that should only leak once per video, not during the playback of a single video.
- I miss the buf->Unlock() on each frame. 
But after the two fixes, the process is still leaking. The leak is inside the MF library, when calling the pSourceReader->ReadSample, but we just need to call pVideoSample->Release to free the resources. So I can't find the problem.
I have tried with videos of 2Gb and 7Gb, and even when the memory is going up, it's not even close to the size of the stream. 
Can you try with the updated source?

**Comment by yabadabu** [comment]
I confirm this is leaking like crazy, and goes slower and slower. Let me check for solutions.

**Comment by yabadabu** [comment]
Hi, I found the solution, disabling the audio stream fixes the leak. 
pSourceReader->SetStreamSelection(MF_SOURCE_READER_FIRST_AUDIO_STREAM, FALSE);
