### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by sevstels** [yabadabu/dx11_video_texture#4]
Hi
Build example in VS2019. The application is built without errors, but it does not start. 
Func: video.create("data/demo.mp4")) ends with error.

An exception was raised at address 0x00007FFFE616BA99 (KernelBase.dll) in dx11_video_decoder.exe: WinRT originate error - 0xC00D36B3 : 'An invalid stream number was submitted.'
The dx11_video_decoder.exe programme terminated with code 0 (0x0).

**Comment by yabadabu** [comment]
Hi 
Thanks for detecting the problem. It's now fixed in commit 0393e8a
The problem was checking for errors when disabling the audio stream when the stream has no audio. Disabling the audio was introduced to remove a leak. Now I disable all the streams and enable just the video.
